twitch:
  bot:
    prefix: 
    channel: 
    channel_id: 
    username: 
    oauth: 
  helix:
    client_id:
    client_secret:
    eventsub_secret:
    redirect_uri:

turso:
  url: 

api_keys:
  lastfm: